-- SQL - The language of Databases
-- SQL (Structured Query Language) is the language you use to talk to a database.
-- Every time you want to store, read, update or delete data you write SQL
-- It's not a programming language like Python - it's a query language.
-- You describe what you want, not how to get it.
-- Database -> Excel but more powerful
-- Excel:
-- | Name    | Age | City    |
-- |---------|-----|---------|
-- | Sergiu  | 20  | Sibiu   |
-- | Alex    | 25  | Cluj    |